Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  # config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.define "front" do |front|
    front.vm.network "private_network", ip: "172.28.128.12"
  end

  config.vm.define "api" do |api|
    api.vm.network :forwarded_port, guest: 3000, host: 3000
    api.vm.network "private_network", ip: "172.28.128.11"
  end

  config.vm.define "db" do |db|
    db.vm.network :forwarded_port, guest: 3306, host: 3306
    db.vm.network "private_network", ip: "172.28.128.10"
  end
end
