version: "3.5"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    expose:
      - "8080"
      - "50000"
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
    name: jenkins
